### ISSUE TITLE
Instagram Not Working

### ISSUE THREAD

**Issue by tehloxely** [dadler/thumbnail-zoom#245]
Instagram used to work, it doesn't now. It acts as if it is going to 'zoom' but it doesn't.

**Comment by dadler** [comment]
How can I reproduce this?  Do you have a specific web address URL and particular image on that page where it's not working?

**Comment by tehloxely** [comment]
It's any image on any page. I am using Firefox on Win7.

**Comment by dadler** [comment]
It is working for me on pages which look similar.  

I see that you are getting the TZP cursor with two dots ("..").  That means it's working on retrieving the pop-up.  For me, the pop-up appears about a second later.  If you move too fast to another image, it won't appear.  

What happens if you keep the mouse over the image longer (e.g. up to 10 seconds)?  Does a pop-up ever appear?  Do you see a yellow TZP error indicator cursor?

**Comment by tehloxely** [comment]
The pop-up for the hovering literally does only that, no matter how long I hold the cursor over an image. And my cursor stays as a hand the entire time.

**Comment by dadler** [comment]
This is fixed now, in version 4.1beta3.  https://addons.mozilla.org/en-US/firefox/addon/thumbnail-zoom-plus/versions/beta
